import assert from 'node:assert/strict';
import * as G from './dist/game.mjs';
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function ready(){const s=G.createGame();G.autoDeploy(s);s.rocket.wounds=0;G.begin(s);G.nextPhase(s);return s;}
test('20 models occupy exactly 125 x 100 mm',()=>{assert.equal(G.SIZE.w*25.4,125);assert.equal(G.SIZE.h*25.4,100);});
test('deployment requires the whole footprint within its zone',()=>{const s=G.createGame();assert.throws(()=>G.place(s,'A1',20,36),/zone/);G.place(s,'A1',20,36+G.SIZE.h/2);assert.throws(()=>G.place(s,'A2',20,40),/between/);assert.throws(()=>G.begin(s),/eight/);});
test('all eight legal blocks begin with the red army',()=>{const s=ready();assert.equal(s.units.length,8);assert.equal(s.team,'ash');assert.equal(s.stage,'movement');s.units.forEach(u=>assert.equal(G.checkPosition(s,u,u.x,u.y,true),null));});
test('advance limit, turn ownership and single move enforced',()=>{const s=ready();assert.throws(()=>G.move(s,'A1',4,'advance'),/allowance/);assert.throws(()=>G.move(s,'I1',3,'advance'),/active/);G.move(s,'A1',3,'advance');assert.equal(G.getUnit(s,'A1').y,39);assert.throws(()=>G.move(s,'A1',1,'advance'),/active/);});
test('march distance does not require dice when no enemy is nearby',()=>{const s=ready();assert.equal(G.needsMarchTest(s,G.getUnit(s)),false);G.move(s,'A1',6,'march');assert.equal(G.getUnit(s).y,36);});
test('nearby enemy requires test; failure permits normal movement only',()=>{const s=ready();G.getUnit(s,'A1').y=25;G.getUnit(s,'I1').y=14;assert.equal(G.needsMarchTest(s,G.getUnit(s)),true);assert.throws(()=>G.move(s,'A1',6,'march'),/test/);assert.equal(G.marchTest(s,'A1',[6,6]),false);assert.throws(()=>G.marchTest(s,'A1',[1,1]),/already/);assert.throws(()=>G.move(s,'A1',6,'march'),/failed/);G.move(s,'A1',3,'advance');G.undo(s);assert.equal(G.getUnit(s).marchTest,false);});
test('passed test and undo preserve result',()=>{const s=ready();G.getUnit(s,'A1').y=25;G.getUnit(s,'I1').y=14;assert.equal(G.marchTest(s,'A1',[4,5]),true);G.move(s,'A1',5,'march');G.undo(s);assert.equal(G.getUnit(s).y,25);assert.equal(G.getUnit(s).marchTest,true);});
test('movement path prevents tunnelling through another regiment',()=>{const s=ready();G.getUnit(s,'A1').y=32;G.getUnit(s,'A2').x=18;G.getUnit(s,'A2').y=26;assert.throws(()=>G.move(s,'A1',6,'march'),/between|blocks/);});
test('minimum separation and table boundaries are enforced',()=>{const s=ready();G.getUnit(s,'A1').y=6;G.getUnit(s,'A1').x=4;assert.throws(()=>G.move(s,'A1',6,'march'),/battlefield/);const a=G.getUnit(s,'A1'),b=G.getUnit(s,'A2');b.x=a.x;b.y=a.y+G.SIZE.h+1;assert.ok(Math.abs(G.gap(a,b)-1)<1e-9);assert.equal(G.checkPosition(s,b,b.x,b.y),null);});
test('turn, round and movement flags reset correctly',()=>{const s=ready();G.move(s,'A1',3,'advance');G.nextPhase(s);G.nextPhase(s);G.nextPhase(s);assert.equal(s.team,'iron');assert.equal(s.round,1);assert.equal(s.history.length,0);G.move(s,'I1',3,'advance');assert.equal(G.getUnit(s,'I1').y,9);G.nextPhase(s);G.nextPhase(s);assert.equal(s.round,2);assert.equal(s.team,'ash');assert.ok(s.units.every(u=>!u.moved&&u.marchTest===null));});
test('dice counts and bounds',()=>{assert.deepEqual(G.rollD6(2,()=>0),[1,1]);assert.deepEqual(G.rollD6(2,()=>.99999),[6,6]);for(const n of [0,21,1.5,NaN])assert.throws(()=>G.rollD6(n));});
console.log(`${passed} movement checks passed.`);

test('phase sequence skips Shooting when no target is legal',()=>{const s=G.createGame();G.autoDeploy(s);s.rocket.wounds=0;G.begin(s);assert.equal(s.stage,'strategy');assert.equal(G.canAct(s,G.getUnit(s)),false);G.nextPhase(s);assert.equal(s.stage,'movement');G.move(s,'A1',3,'advance');G.nextPhase(s);assert.equal(s.stage,'combat');assert.equal(G.canAct(s,G.getUnit(s,'A2')),false);assert.equal(s.history.length,0);G.nextPhase(s);assert.equal(s.stage,'strategy');assert.equal(s.team,'iron');assert.equal(s.round,1);for(let i=0;i<3;i++)G.nextPhase(s);assert.equal(s.stage,'strategy');assert.equal(s.team,'ash');assert.equal(s.round,2);});
