import assert from 'node:assert/strict';import * as G from './dist/game.mjs';
const test=(name,fn)=>{fn();console.log('PASS '+name)};
function fightFixture(){const s=G.createGame();G.autoDeploy(s);G.begin(s);G.nextPhase(s);const a=G.getUnit(s,'A1'),b=G.getUnit(s,'I1');Object.assign(a,{x:18,y:22,engaged:'I1',charge:{status:'success',distance:4,face:'front'}});Object.assign(b,{x:18,y:22-G.SIZE.h,engaged:'A1'});s.stage='combat';return s;}
test('initiative advantage removes casualties before defender attacks',()=>{const s=fightFixture();let i=0;const r=G.resolveCombat(s,'A1',()=>[...Array(6).fill(.999),...Array(5).fill(.999),0,...Array(50).fill(0)][i++]);assert.equal(r.stages[0].initiative,5);assert.equal(r.stages[0].unsaved,5);assert.ok(r.stages[1].fighters<10);assert.equal(G.aliveCount(G.getUnit(s,'I1')),15);assert.equal(G.commandAlive(G.getUnit(s,'I1'),'C'),true);assert.equal(r.outcome,'give-ground');assert.deepEqual(r.breakDice,[1,1]);});
test('equal initiative attacks are simultaneous',()=>{const s=fightFixture();G.getUnit(s,'A1').charge=null;let i=0;const rolls=[...Array(11).fill(.999),...Array(11).fill(.999),...Array(11).fill(0),...Array(11).fill(.999),...Array(11).fill(.999),...Array(11).fill(0)];const r=G.resolveCombat(s,'A1',()=>rolls[i++]);assert.equal(r.stages[0].fighters,10);assert.equal(r.stages[1].fighters,10);assert.equal(G.aliveCount(G.getUnit(s,'A1')),9);assert.equal(G.aliveCount(G.getUnit(s,'I1')),9);assert.equal(r.outcome,'draw');assert.equal(G.combatPairs(s).length,0);});
test('normal dice can produce wounds and Parry saves',()=>{const s=fightFixture();let i=0;const sequence=[...Array(5).fill(.51),0,...Array(5).fill(.7),...Array(5).fill(.17)];const r=G.resolveCombat(s,'A1',()=>sequence[i++]??0);assert.equal(r.stages[0].hits,5);assert.equal(r.stages[0].wounds,5);assert.equal(r.stages[0].unsaved,5);});
test('winner scores rank, Close Order and Standard bonuses',()=>{const s=fightFixture(),r=G.resolveCombat(s,'A1',()=>0);assert.equal(r.score.A1.ranks,2);assert.equal(r.score.A1.closeOrder,1);assert.equal(r.score.A1.standard,1);assert.equal(r.score.A1.total,4);assert.equal(r.outcome,'draw');});
test('break test and aftermath must complete before phase advancement',()=>{const s=fightFixture();let i=0;const dice=[...Array(6).fill(.999),...Array(5).fill(.999),0,...Array(50).fill(0)];G.resolveCombat(s,'A1',()=>dice[i++]);assert.ok(s.pendingCombat);assert.throws(()=>G.nextPhase(s),/Resolve/);const p=G.finishCombat(s,'follow',()=>0);assert.equal(p.outcome,'give-ground');assert.equal(s.pendingCombat,null);G.nextPhase(s);assert.equal(s.stage,'strategy');});
test('dead slots cannot attack or be highlighted',()=>{const s=fightFixture(),a=G.getUnit(s,'A1');a.deadModels=[0,1];assert.equal(G.modelSquares(s,a).filter(m=>m.fighting).length,3);assert.equal(G.modelSquares(s,a).filter(m=>m.dead).length,2);});
test('fleeing regiments must attempt Rally and cannot move until successful',()=>{const s=G.createGame();G.autoDeploy(s);G.begin(s);const a=G.getUnit(s,'A1');a.fleeing=true;assert.throws(()=>G.nextPhase(s),/rally/);const failed=G.rally(s,'A1',()=>.999);assert.equal(failed.success,false);G.nextPhase(s);assert.equal(G.canAct(s,a),false);s.stage='strategy';s.team='ash';a.rallyAttempted=false;const passed=G.rally(s,'A1',()=>0);assert.equal(passed.success,true);G.nextPhase(s);assert.equal(G.canAct(s,a),true);assert.match(G.chargePlan(s,a,G.getUnit(s,'I1')).error,/cannot charge/);});
test('staged combat shows initiative, attacks in order, then moves loser before winner choice',()=>{const s=fightFixture();const session=G.beginCombat(s,'A1');assert.equal(session.groups[0],5);assert.equal(session.groups[1],2);assert.throws(()=>G.nextPhase(s),/Resolve/);let i=0;G.fightCombatStep(s,()=>[...Array(6).fill(.999),...Array(5).fill(.999),0,...Array(50).fill(0)][i++]??0);assert.equal(s.combatSession.step,1);G.fightCombatStep(s,()=>0);const result=G.compareCombat(s);assert.equal(result.winner,'A1');G.rollCombatBreak(s,()=>0);if(s.pendingCombat.stage==='loser-choice')G.chooseLoserAction(s,'fall-back');assert.equal(s.pendingCombat.stage,'declare','the winner declares before the loser moves');G.declarePursuit(s,'A1','restrain',null,()=>0);const loser=G.getUnit(s,s.pendingCombat.loser),before={x:loser.x,y:loser.y};assert.equal(s.pendingCombat.stage,'retreat');G.moveCombatLoser(s,()=>0);assert.equal(s.pendingCombat.stage,'winner-choice');assert.ok(loser.x!==before.x||loser.y!==before.y);G.winnerCombat(s,'restrain',()=>0);assert.equal(s.pendingCombat,null);});
