import assert from 'node:assert/strict';
import * as G from './dist/game.mjs';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS '+name);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function fixture(distance=7){const s=G.createGame();G.autoDeploy(s);s.rocket.wounds=0;G.begin(s);G.nextPhase(s);Object.assign(G.getUnit(s,'A1'),{x:18,y:25});Object.assign(G.getUnit(s,'I1'),{x:18,y:25-G.SIZE.h-distance});s.movementStep='declare';return s;}
function roll(s,dice){G.declareCharge(s,'A1','I1');G.chargeReaction(s,'A1','hold');G.finishDeclarations(s);return G.resolveCharge(s,'A1',dice);}
test('charge range uses highest of two dice, not sum',()=>{const s=fixture(8);const r=roll(s,[4,3]);assert.equal(r.range,7);assert.equal(r.success,false);near(r.distance,4);assert.equal(G.getUnit(s,'A1').moved,true);});
test('successful charge contacts target and locks both units',()=>{const s=fixture(7);const r=roll(s,[2,4]);assert.equal(r.success,true);near(G.gap(G.getUnit(s,'A1'),G.getUnit(s,'I1')),0);assert.equal(G.getUnit(s,'I1').engaged,'A1');assert.equal(G.canAct(s,G.getUnit(s,'A1')),false);assert.throws(()=>G.undo(s),/No move/);});
test('failure cannot reroll, move again, or undo',()=>{const s=fixture(8);roll(s,[1,1]);assert.throws(()=>G.resolveCharge(s,'A1',[6,6]));assert.throws(()=>G.move(s,'A1',1,'advance'));assert.throws(()=>G.undo(s));near(G.getUnit(s,'A1').y,24);});
test('declarations lock before rolls and prevent regular movement',()=>{const s=fixture();G.declareCharge(s,'A1','I1');assert.throws(()=>G.move(s,'A2',1,'advance'),/Resolve/);assert.throws(()=>G.nextPhase(s),/Resolve/);assert.throws(()=>G.resolveCharge(s,'A1',[4,4]));G.cancelCharge(s,'A1');G.finishDeclarations(s);assert.equal(s.movementStep,'remaining');assert.throws(()=>G.declareCharge(s,'A1','I1'));});
test('maximum range and front arc are enforced',()=>{const s=fixture(10);assert.match(G.chargePlan(s,G.getUnit(s,'A1'),G.getUnit(s,'I1')).error,/9/);G.getUnit(s,'I1').y=32;assert.match(G.chargePlan(s,G.getUnit(s,'A1'),G.getUnit(s,'I1')).error,/front arc/);});
test('charge path cannot tunnel through friendly unit',()=>{const s=fixture(8);Object.assign(G.getUnit(s,'A2'),{x:18,y:19});assert.match(G.chargePlan(s,G.getUnit(s,'A1'),G.getUnit(s,'I1')).error,/blocks/);});
test('invalid dice leave declared charge untouched',()=>{const s=fixture();G.declareCharge(s,'A1','I1');G.chargeReaction(s,'A1','hold');G.finishDeclarations(s);for(const d of [[0,5],[7,1],[2],[2.5,3]])assert.throws(()=>G.resolveCharge(s,'A1',d));assert.equal(G.getUnit(s,'A1').charge.status,'declared');});
test('engagement persists across turns',()=>{const s=fixture(4);roll(s,[1,1]);G.nextPhase(s);assert.equal(s.stage,'combat');assert.throws(()=>G.nextPhase(s),/Resolve every combat/);G.resolveCombat(s,'A1',()=>0);G.nextPhase(s);assert.equal(s.team,'iron');assert.equal(G.getUnit(s,'I1').engaged,'A1');assert.equal(G.canAct(s,G.getUnit(s,'I1')),false);});
test('remaining moves close declarations even through direct engine API',()=>{const s=fixture();G.move(s,'A2',1,'advance');assert.equal(s.movementStep,'remaining');assert.throws(()=>G.declareCharge(s,'A1','I1'));});
test('flank contact preserves unit footprints',()=>{const s=fixture();Object.assign(G.getUnit(s,'I1'),{heading:90,y:25-(G.SIZE.w+G.SIZE.h)/2-5});const p=G.chargePlan(s,G.getUnit(s,'A1'),G.getUnit(s,'I1'));assert.equal(p.error,undefined);assert.match(p.face,/flank/);const r=roll(s,[3,1]);assert.ok(r.success);near(G.gap(G.getUnit(s,'A1'),G.getUnit(s,'I1')),0);});
console.log(`${n} charge checks passed.`);
test('a single wheel is included in the charge distance',()=>{const s=fixture(),u=G.getUnit(s,'A1'),t=G.getUnit(s,'I1');const after=G.wheelPose(u,20),target=G.forwardPose(after,G.SIZE.h+3);Object.assign(t,{x:target.x,y:target.y,heading:200});const p=G.chargePlan(s,u,t);assert.equal(p.error,undefined);near(p.cost,G.wheelCost(20)+3);const r=roll(s,[6,1]);assert.ok(r.success);near(G.heading(u),20);near(G.gap(u,t),0);});
test('all declared charges resolve before remaining moves',()=>{const s=fixture(4);Object.assign(G.getUnit(s,'A2'),{x:36,y:25});Object.assign(G.getUnit(s,'I2'),{x:36,y:25-G.SIZE.h-4});G.declareCharge(s,'A1','I1');G.declareCharge(s,'A2','I2');G.chargeReaction(s,'A1','hold');G.chargeReaction(s,'A2','hold');G.finishDeclarations(s);G.resolveCharge(s,'A1',[1,1]);assert.equal(s.movementStep,'charges');assert.throws(()=>G.move(s,'A3',1,'advance'));G.resolveCharge(s,'A2',[2,2]);assert.equal(s.movementStep,'remaining');G.move(s,'A3',1,'advance');});
test('charge steps are skipped when no unit can charge',()=>{const s=G.createGame();G.autoDeploy(s);G.begin(s);G.nextPhase(s);assert.equal(s.movementStep,'remaining');});
test('an offset approach gets a free second wheel after touching',()=>{const s=fixture(4),u=G.getUnit(s,'A1'),t=G.getUnit(s,'I1');t.x+=1.5;const p=G.chargePlan(s,u,t);assert.equal(p.error,undefined);assert.ok(Math.abs(p.alignAngle)>1,`second wheel ${p.alignAngle}`);assert.ok(Math.abs(p.angle)<=90);assert.ok(p.cost<=9);near(G.gap(p.end,t),0);});
test('flank and rear charge facings remain fixed from declaration',()=>{const s=fixture(4),u=G.getUnit(s,'A1'),t=G.getUnit(s,'I1');Object.assign(t,{x:18,y:19,heading:90});let p=G.chargePlan(s,u,t);assert.equal(p.error,undefined);assert.equal(p.face,'right flank');Object.assign(t,{x:18,y:19,heading:0});Object.assign(u,{y:25,heading:0});s.movementStep='declare';p=G.chargePlan(s,u,t);assert.equal(p.error,undefined);assert.equal(p.face,'rear');});
test('every defender chooses a legal charge reaction',()=>{const s=fixture(4);assert.equal(G.declareCharge(s,'A1','I1').reaction,'pending');assert.throws(()=>G.finishDeclarations(s),/reaction/);assert.throws(()=>G.chargeReaction(s,'A1','stand-shoot'),/cannot Stand/);assert.equal(G.chargeReaction(s,'A1','hold').choice,'hold');G.finishDeclarations(s);assert.equal(s.movementStep,'charges');});
test('Flee moves 2D6 away and an insufficient charge pursues without combat',()=>{const s=fixture(4),target=G.getUnit(s,'I1'),start=target.y;G.declareCharge(s,'A1','I1');const reaction=G.chargeReaction(s,'A1','flee',()=>0);assert.deepEqual(reaction.fleeDice,[1,1]);near(target.y,start-2);assert.equal(target.fleeing,true);G.finishDeclarations(s);const result=G.resolveCharge(s,'A1',[2,1]);assert.equal(result.success,false);assert.equal(result.runDown,false);assert.equal(G.getUnit(s,'A1').engaged,null);assert.ok(result.distance>0);});
test('a reachable fleeing target is run down after the charge roll',()=>{const s=fixture(4),target=G.getUnit(s,'I1');G.declareCharge(s,'A1','I1');G.chargeReaction(s,'A1','flee',()=>0);G.finishDeclarations(s);const result=G.resolveCharge(s,'A1',[6,1]);assert.equal(result.runDown,true);assert.equal(target.destroyed,true);assert.equal(target.x,null);assert.equal(G.getUnit(s,'A1').engaged,null);});
test('already fleeing defenders must Flee and can leave the battlefield',()=>{const s=fixture(8),target=G.getUnit(s,'I1');target.fleeing=true;G.declareCharge(s,'A1','I1');assert.throws(()=>G.chargeReaction(s,'A1','hold'),/must Flee/);const reaction=G.chargeReaction(s,'A1','flee',()=>.99);assert.equal(reaction.fledOffBoard,true);assert.equal(target.destroyed,true);assert.equal(target.fleeing,false);assert.equal(G.aliveCount(target),0);G.finishDeclarations(s);const result=G.resolveCharge(s,'A1',[4,1]);assert.equal(result.success,false);});


